# network: "finney"
network: "subvortex"
interval: 60  # seconds
threshold: 1.  # default percent change

# Alert settings
alerts_on: true
alert_positive: "assets/sounds/yeah.mp3"
alert_negative: "assets/sounds/wtf.mp3"
alert_volume: .5  # 50% volume

# List of subnets to monitor
subnets:
  - netuid: 56
  - netuid: 8
  - netuid: 25
  - netuid: 34
  - netuid: 5
  - netuid: 19
  - netuid: 13
    threshold: .5
  - netuid: 52
    threshold: .5 
  - netuid: 68
    threshold: .5




