network: "finney"
interval: 300  # seconds
alert_sound: "alert.mp3"

# List of subnets to monitor
subnets:
  - netuid: 4
    threshold: 1.0  # percentage
  - netuid: 8
    threshold: 1.0
  - netuid: 13
    threshold: 1.0 
  - netuid: 34
    threshold: 1.0
  - netuid: 64
    threshold: 1.0 