network: "finney"
interval: 20  # seconds
threshold: 1.  # default percent change

# Alert settings
alerts_on: true
alert_positive: "assets/sounds/yeah.mp3"
alert_negative: "assets/sounds/wtf.mp3"
alert_volume: .75  # 50% volume

# List of subnets to monitor
subnets:
  - netuid: 75
  
  


