network: "finney"
# network: "subvortex"
interval: 15  # seconds
threshold: .25  # default percent change

# Alert settings
alerts_on: true
alert_positive: "assets/sounds/positive.mp3"
alert_negative: "assets/sounds/negative.mp3"
alert_volume: .3  # 50% volume

# Alarm settings
alarm_enabled: true
alarm_threshold: 3.0  # Trigger alarm at 3% change
alarm_negative_only: true  # Whether to only trigger alarms for negative changes
alarm_sound_positive: "assets/sounds/alarm.mp3"
alarm_sound_negative: "assets/sounds/alarm.mp3"
alarm_volume: 1.0  # 100% volume

notification_url: "https://taostats.io/subnets/"

# List of subnets to monitor
subnets:
  - netuid: 3   # templar
  - netuid: 12   # horde
  - netuid: 14   # TAOhash
  - netuid: 19   # nineteen
  - netuid: 33   # readyAI
  - netuid: 44   # score
  - netuid: 51   # celium
  - netuid: 56   # gradients
  - netuid: 64   # chutes
  - netuid: 68   # nova
  - netuid: 75   # hippius
  - netuid: 85   # vidaio

subnets-org:
  # - netuid: 1   # apex
  - netuid: 3   # templar
  - netuid: 4   # targon
  # - netuid: 5   # kaito
  # - netuid: 7   # subvortex
  # - netuid: 8   # ptn
  - netuid: 12   # horde
  - netuid: 13   # datavers
  - netuid: 14   # TAOhash
  # - netuid: 17   # 404
  - netuid: 18   # zeus
  - netuid: 19   # nineteen
  # - netuid: 26   # storb
  # - netuid: 23   # zuvu
  # - netuid: 31   # nullUntilBoot NAS
  - netuid: 33   # readyAI
  # - netuid: 34   # bitmind
  # - netuid: 37   # finetune
  - netuid: 38   # dist training
    # threshold: 2.
  # - netuid: 41   # sportsensor
  - netuid: 44   # score
  - netuid: 51   # celium
  # - netuid: 52   # dojo
  - netuid: 56   # gradients
  # - netuid: 61   # redTeam
  - netuid: 64   # chutes
  # - netuid: 65   # TPN
  - netuid: 68   # nova
  # - netuid: 27   # NI compute
  - netuid: 75    # hippius
    # threshold: 1.
  # - netuid: 76    # safe scan
  # - netuid: 81   # patrol
  