network: "finney"
# network: "subvortex"
interval: 300  # seconds
threshold: .5  # default percent change

# Alert settings
alerts_on: false
alert_positive: "assets/sounds/positive.mp3"
alert_negative: "assets/sounds/negative.mp3"
alert_volume: .8  # 50% volume

# Alarm settings
alarm_enabled: true
alarm_threshold: 5.0  # Trigger alarm at 10% drop
alarm_sound: "assets/sounds/alarm.mp3"
alarm_volume: 1.0  # 100% volume

notification_url: "https://taostats.io/subnets/"

# List of subnets to monitor
subnets:
  - netuid: 3   # templar
  # - netuid: 19   # nineteen
  - netuid: 56   # gradients
  - netuid: 64   # chutes
  # - netuid: 68   # nova