network: "finney"
interval: 10  # seconds
threshold: 5.  # default percent change

# Alert settings
alerts_on: true
alert_positive: "assets/sounds/yeah.mp3"
alert_negative: "assets/sounds/wtf.mp3"
alert_volume: 1.  # 50% volume

notification_url: "https://taostats.io/subnets/"

# List of subnets to monitor
subnets:
  - netuid: 64  
    threshold: .0
  - netuid: 70
    threshold: 1.
  - netuid: 75
  - netuid: 76

# Backup List of subnets to monitor
subnets-stake:
  - netuid: 8
  - netuid: 56
  - netuid: 37
  - netuid: 25
  - netuid: 19