network: "finney"
interval: 300  # seconds
alerts_on: true
alert_positive: "assets/sounds/yeah.mp3"
alert_negative: "assets/sounds/wtf.mp3"

# List of subnets to monitor
subnets:
  - netuid: 4
    threshold: 1. # percentage
  - netuid: 8
    threshold: 1.
  - netuid: 13
    threshold: 1. 
  - netuid: 34
    threshold: 1.
  - netuid: 56
    threshold: 1.
  - netuid: 64
    threshold: 1. 
  - netuid: 68
    threshold: 1. 
