network: "finney"
interval: 10  # seconds
threshold: .5  # default percent change

# Alert settings
alerts_on: true
alert_positive: "assets/sounds/yeah.mp3"
alert_negative: "assets/sounds/wtf.mp3"
alert_volume: .5  # 50% volume

# List of subnets to monitor
subnets:
  - netuid: 13
  - netuid: 52
  - netuid: 73
  - netuid: 74
  


