network: "finney"
# network: "subvortex"
interval: 10  # seconds
threshold: .25  # default percent change

# Alert settings
alerts_on: true
alert_positive: "assets/sounds/positive.mp3"
alert_negative: "assets/sounds/negative.mp3"
alert_volume: 1.  # 50% volume

# Alarm settings
alarm_enabled: true
alarm_threshold: 3.0  # Trigger alarm at 3% change
alarm_negative_only: false  # Whether to only trigger alarms for negative changes
alarm_sound_positive: "assets/sounds/yeah.mp3"
alarm_sound_negative: "assets/sounds/alarm.mp3"
alarm_volume: 1.0  # 100% volume

notification_url: "https://taostats.io/subnets/"

# List of subnets to monitor
subnets:
- netuid: 14   # TAOhash
# - netuid: 12   # horde
# # - netuid: 27   # NIcompute
# - netuid: 33   # readyAI
# # - netuid: 3   # templar

# # - netuid: 19   # nineteen
# # - netuid: 64   # chutes
# # - netuid: 18   # zeus
# - netuid: 21   # omega any2any - low mc/fdv, will buy back alpha
# # - netuid: 75   # hippius

# # - netuid: 15   # d_V
# # - netuid: 56   # gradients
# - netuid: 5   # open kaito
# # - netuid: 17   # 404
# # - netuid: 28   # fish https://www.tao.app/portfolio?coldkey=5Gy1XdCUj3JxaEA2uM9vYmVKii3ech2MbopD5iw6EEZkeWCZ owned 14 and sold it to JJ, he then started to buy up 14 weeks before announcement in small increments to avoid detection, while this is going on he bought LOL 28 for cheap af bc former owner sold all his alpah and it was not as appealing to others to buy, once fish bought 28, he then fudded saying whoever buying this sn will get dumped on while he has been accumulating under his alt wallet, which is now #1 with close to 100k alpha. Fish is not selling this sn to NOBODY. he will build. this is all on chain and dates match. yall can check for yourself if you're not lazy to dig. btw creativebuild and lucian probably thinks the same as they've sorta kinda confirmed
# - netuid: 57   # gaia -> https://x.com/badenglishtea/status/1920485916940153304
# - netuid: 85   # vidaio
